spring:
  security:
    oauth2:
      client:
        # Registration (GOOGLE, KAKAO)
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_PASSWORD:GOOGLE_CLIENT_ID}
            redirect-uri: http://localhost:3000/oauth/google
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client_name: google
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_OAUTH_CLIENT_REDIRECT_URI}
            client-authentication-method: POST
            client_name: kakao
        # Provider (GOOGLE, KAKAO)
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI:GOOGLE_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_TOKEN_URI:GOOGLE_TOKEN}
            user-info-uri: ${GOOGLE_USER_INFO_URI:GOOGLE_USER_INFO_URI}
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI:KAKO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI:https://kauth.kakao.com//oauth/token}
            user-info-uri: ${KAKAO_USER_INFO_URI:https://kapi.kakao.com//v2/user/me}


